
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            games:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_games%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            persons:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_persons%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            project:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_projects%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

    orm:
        default_entity_manager:       default
        auto_generate_proxy_classes: %kernel.debug%
       #auto_mapping: true
                
        entity_managers:
          
            default:
                connection: default
                mappings:
                    CeradUserBundle:   ~
                    CeradGameBundle:   ~
                    CeradPersonBundle: ~
                    CeradProjectBundle: { prefix: Cerad\Bundle\ProjectBundle\Doctrine\Entity }
                    
            project:
                connection: project
                mappings:
                    CeradProjectBundle: { prefix: Cerad\Bundle\ProjectBundle\Doctrine\Entity }
            
            games:
               connection: games
               mappings:
                    CeradGameBundle: ~
               dql:
                    datetime_functions:
                        date:  Cerad\Bundle\GameBundle\Doctrine\DQL\Date
                        time:  Cerad\Bundle\GameBundle\Doctrine\DQL\Time
                        month: Cerad\Bundle\GameBundle\Doctrine\DQL\Month
                        
            persons:
               connection: persons
               mappings:
                    CeradPersonBundle: ~
                    