
cerad_tourn_routes:
  resource: "@CeradTournBundle/Resources/config/routing.yml"
  
cerad_user_routes:
  resource: "@CeradUserBundle/Resources/config/routing.yml"
  
cerad_person_routes:
  resource: "@CeradPersonBundle/Resources/config/routing.yml"

