# ==================================================
# Tournament Routes
#cerad_tourn:
#  resource: "@CeradTournBundle/Resources/config/routing.yml"

    
# ==================================================
# JanrainBundle Stuff
#cerad_janrain:
#    resource: "@CeradJanrainBundle/Resources/config/routing.yml"
#    prefix: /account
